// GENERATED by scripts/setup-mirror.mjs on 2026-09-13T16:27:42.433Z
// Cluster: devnet. Do not edit by hand.
//
// Each entry pairs a mainnet xStock with its stand-in on the write cluster. Prices
// and multipliers on screen come from the mainnet mint; mint and redeem transactions
// go to the write mint. Both are shown wherever it could matter.

export type MirrorEntry = {
  writeMint: string;
  mainnetMint: string;
  /** The mainnet multiplier the mirror was seeded with. */
  seededMultiplier: number;
};

export const MIRROR_CLUSTER = "devnet";

export const MIRROR: Record<string, MirrorEntry> = {
  "AAPLx": {
    writeMint: "7mRaNLFCGKquZwtnY7TkAYM3yiJQPz2QoshRzFofG1tQ",
    mainnetMint: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    seededMultiplier: 1.0032690125398187,
  },
  "AMZNx": {
    writeMint: "H77SXLVDBNLDfDnriTq7ddqQgHN1DYt1caorEWVZo7DY",
    mainnetMint: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    seededMultiplier: 1,
  },
  "COINx": {
    writeMint: "7qqZ6au59LvEZ5kLdkHQHLTAoa4ChkZGNd2qW7DqUz4N",
    mainnetMint: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    seededMultiplier: 1,
  },
  "CRCLx": {
    writeMint: "5gHWN3qcLhqmAoyX4np9UoaRkneCU3xMp6ypjKtbUqUs",
    mainnetMint: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1",
    seededMultiplier: 1,
  },
  "DFDVx": {
    writeMint: "CSa83meegYQUhYv58NqyTmsmT281cWWSXh2qUQrQhQTy",
    mainnetMint: "Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy",
    seededMultiplier: 1.01472895118,
  },
  "GLDx": {
    writeMint: "8MA34o3VcwWy74iVoWbRCJFuGxtA9krnFoPmMaGpuvQR",
    mainnetMint: "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re",
    seededMultiplier: 1,
  },
  "GMEx": {
    writeMint: "CgBobRASdfC25hbvEQiaWwP2pDtG6KTmpie4dnha6dP6",
    mainnetMint: "Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc",
    seededMultiplier: 1.005309167384,
  },
  "GOOGLx": {
    writeMint: "2vy2Ed5GXYzHrn2M3ae1DwidPZPG7nVsjoAm5KovbNGh",
    mainnetMint: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    seededMultiplier: 1.0023772500603487,
  },
  "HOODx": {
    writeMint: "ApBNGf46vAVrD1NRZnPhn5tDqxGdEqn7P5teBRYbwLFr",
    mainnetMint: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg",
    seededMultiplier: 1,
  },
  "MCDx": {
    writeMint: "DjXQHAmwQaBKNe4kTX55gMDW7pSrXxWMqyvmFfVy9P15",
    mainnetMint: "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2",
    seededMultiplier: 1.0211807004882871,
  },
  "METAx": {
    writeMint: "FHqmv8PrG2JHfZKwrPUQ6G43yhFBDmoqWaHeRtYHyhRA",
    mainnetMint: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    seededMultiplier: 1.002298265651938,
  },
  "MSFTx": {
    writeMint: "5L46rBv6YAaB14Vax8jNRGu94BQmnK3HTWqqMj4nu5xe",
    mainnetMint: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
    seededMultiplier: 1.0059033904787456,
  },
  "MSTRx": {
    writeMint: "6uhjUMFJNE1zeAgK4q8hFDHBgwbZguuHc72W8x7XGVbd",
    mainnetMint: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    seededMultiplier: 1,
  },
  "NVDAx": {
    writeMint: "3Z439JmXcUyfuC1aBZZcWJdeMophCz7AvrXG4ZAHz5CT",
    mainnetMint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    seededMultiplier: 1.001701196801074,
  },
  "PLTRx": {
    writeMint: "33HyGpoqxXvFbhZ5FjTYGZYukhN9NaBfAEs4dyh46Ls5",
    mainnetMint: "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4",
    seededMultiplier: 1,
  },
  "QQQx": {
    writeMint: "GUSGkqJevsaHHA1cco7DmLeFxqh1RxHdCjYBMQRi6zfy",
    mainnetMint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    seededMultiplier: 1.0027250296551051,
  },
  "SPCXx": {
    writeMint: "9Je8WPgC71nyhQMQcbWVvoYXvTApUpcLMBmj5hJM6F1D",
    mainnetMint: "Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8",
    seededMultiplier: 1,
  },
  "SPYx": {
    writeMint: "7gCq8ELcQ8cSmbTwfoQtE9AsyeBza1v2BQoPDgW6gVTA",
    mainnetMint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    seededMultiplier: 1.005714560286254,
  },
  "STRCx": {
    writeMint: "5eHUQBS6UkAYJ1mix3LwxqFwVaFQeNgFJJJZynhC92u1",
    mainnetMint: "Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH",
    seededMultiplier: 1.0808929977256367,
  },
  "TSLAx": {
    writeMint: "H3v73EEPf1uw6x5E8AAD32aZLUqEpJEd3Xe9wa8WM9pJ",
    mainnetMint: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    seededMultiplier: 1,
  },
};

export const HAS_MIRROR = true;
