// GENERATED by scripts/setup-mirror-prestocks.mjs on 2026-09-18T07:33:11.782Z
// Cluster: devnet. Do not edit by hand.

export type PreStockMirrorEntry = {
  writeMint: string;
  mainnetMint: string;
  transferFeeBps: number | null;
};

export const PRESTOCKS_MIRROR_CLUSTER = "devnet";

export const PRESTOCKS_MIRROR: Record<string, PreStockMirrorEntry> = {
  "ANDURIL": {
    writeMint: "7Te8MEevfBsVguWtzy97GM77ixYTrE3WyWuy4eTeHP9a",
    mainnetMint: "PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB",
    transferFeeBps: 50,
  },
  "ANTHROPIC": {
    writeMint: "BYU3RmW2ggqwxbCPBpHeG8KbU23QkmdNDpf1jRpodLVN",
    mainnetMint: "Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw",
    transferFeeBps: 50,
  },
  "FIGUREAI": {
    writeMint: "5ZbDKp9DwivrUczqqwGxt41ZexqJ7KDwbQJ3Hg2bk7f3",
    mainnetMint: "PreZad18qfPtbxNpMtMuAuX2zVpvkEU8DnJx56faCWd",
    transferFeeBps: 50,
  },
  "KALSHI": {
    writeMint: "BNM9jKDkvRfNPrioVf2CL9U8X1tzmWKzWtYM5KZJrVSp",
    mainnetMint: "PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua",
    transferFeeBps: 50,
  },
  "NEURALINK": {
    writeMint: "5qfQGDfnR5NDWBDNhwJ2r62vJ5s3rgpnBp1Z62dF4PUH",
    mainnetMint: "PrekqLJvJ3qVdXmBGDiexvwUTF4rLFDa6HWS4HJbw9S",
    transferFeeBps: 50,
  },
  "OPENAI": {
    writeMint: "4nqMAQ4yaFRc1rtn6otoA6FYWvtz27vRThuBqneALpfu",
    mainnetMint: "PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF",
    transferFeeBps: 50,
  },
  "POLYMARKET": {
    writeMint: "G94bHKzLbagabMjRkxEyaZxVV3Fo6R1gU27LxxvyM7En",
    mainnetMint: "Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP",
    transferFeeBps: 50,
  },
  "SPACEX": {
    writeMint: "E4KjtaBeGGkZD2s6kuFeTq3VmdreDLXR19vCSem6pnQE",
    mainnetMint: "PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh",
    transferFeeBps: 50,
  },
};
