// GENERATED by scripts/setup-mirror.mjs on 2026-09-13T12:20:10.226Z
// Cluster: localnet. Do not edit by hand.
//
// Each entry pairs a mainnet xStock with its stand-in on the write cluster. Prices
// and multipliers on screen come from the mainnet mint; mint and redeem transactions
// go to the write mint. Both are shown wherever it could matter.

export type MirrorEntry = {
  writeMint: string;
  mainnetMint: string;
  /** The mainnet multiplier the mirror was seeded with. */
  seededMultiplier: number;
};

export const MIRROR_CLUSTER = "localnet";

export const MIRROR: Record<string, MirrorEntry> = {
  "AAPLx": {
    writeMint: "ChfDStqSFdEcLWdFgFm74WLgFX1a5ZeNq91ZcXSfVew",
    mainnetMint: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    seededMultiplier: 1.0032690125398187,
  },
  "AMZNx": {
    writeMint: "2VtittF6rWsA7boV5zvicAKd12KjRb1WZSuZ7kpYrwcE",
    mainnetMint: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    seededMultiplier: 1,
  },
  "COINx": {
    writeMint: "Z9drwopdPsQtE9kvE4e1YRB1RWAuvzLoqRHnoyFMHMx",
    mainnetMint: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    seededMultiplier: 1,
  },
  "CRCLx": {
    writeMint: "SmgMdGBVJ1XVcFyFTVYBRT9J36iaWiM95jNRZjugXyV",
    mainnetMint: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1",
    seededMultiplier: 1,
  },
  "DFDVx": {
    writeMint: "3L8wh9kmq7H84tHyuHjgNPhg85rLL1HyF8oUbdzzqkFX",
    mainnetMint: "Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy",
    seededMultiplier: 1.01472895118,
  },
  "GLDx": {
    writeMint: "3Jhjmud5HmfteSN77o5kUXDnP4xwQgeeqxjXfMG2SPMe",
    mainnetMint: "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re",
    seededMultiplier: 1,
  },
  "GMEx": {
    writeMint: "AfMK1cEXtXXEehYZxpfWA3NEg5AEiJzd8SdJDRTFkMme",
    mainnetMint: "Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc",
    seededMultiplier: 1.005309167384,
  },
  "GOOGLx": {
    writeMint: "HvapEY6ZZ2fWy2UtPVjmVSYCHYtCjA6HnYk1vLRaxqQs",
    mainnetMint: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    seededMultiplier: 1.0023772500603487,
  },
  "HOODx": {
    writeMint: "GYVyWZsXDvEgh863KkJves38dATcxJfSWod5boY2AJE4",
    mainnetMint: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg",
    seededMultiplier: 1,
  },
  "MCDx": {
    writeMint: "D4RGLeJ9wAgAvdcCrgMH34edpMuUDvLSRspWALmTyGuF",
    mainnetMint: "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2",
    seededMultiplier: 1.0211807004882871,
  },
  "METAx": {
    writeMint: "2MDMCzscCr3kH5LgTzU11u2izqXARPxTPRcGR2NuoPnH",
    mainnetMint: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    seededMultiplier: 1.002298265651938,
  },
  "MSFTx": {
    writeMint: "4EQHdnhdJzCEzofNo2CTUapdCZD9sSvfMa3RAwpm5bqm",
    mainnetMint: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
    seededMultiplier: 1.0059033904787456,
  },
  "MSTRx": {
    writeMint: "6oWxk6H9yYu4qQrCnRYGmPeXPp2dmWco7LNC8qSEv3AF",
    mainnetMint: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    seededMultiplier: 1,
  },
  "NVDAx": {
    writeMint: "CfTiTW7ZCrLbpXif9Fd2AgoQd5bJkP1xShNo3P7aQT7q",
    mainnetMint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    seededMultiplier: 1.001701196801074,
  },
  "PLTRx": {
    writeMint: "GJYVYHMYiuqe5XnHtPCtqqSHmMRyDjxLMSj86qgymjiC",
    mainnetMint: "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4",
    seededMultiplier: 1,
  },
  "QQQx": {
    writeMint: "5M4tCyc8MSFtkVph9KV9D2KiVpG9xr83ssDx94DnPrnu",
    mainnetMint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    seededMultiplier: 1.0027250296551051,
  },
  "SPCXx": {
    writeMint: "2ZhjBETjxx3yZzAvxdhifhp1vHqwHxTaV9Y7X9k5LsH2",
    mainnetMint: "Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8",
    seededMultiplier: 1,
  },
  "SPYx": {
    writeMint: "CfS7eMByR2pTqPF345icYBYh9stwvCc3j5EpvHWhJ8uG",
    mainnetMint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    seededMultiplier: 1.005714560286254,
  },
  "STRCx": {
    writeMint: "AhaGWPERkXSYPkWFQyohinb3KkbykSjzE8EsUwyg2T1m",
    mainnetMint: "Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH",
    seededMultiplier: 1.0808929977256367,
  },
  "TSLAx": {
    writeMint: "DbBNsj2rdHfwWXbayKSZZej52gbX1nGStV6JeqHY6u4k",
    mainnetMint: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    seededMultiplier: 1,
  },
};

export const HAS_MIRROR = true;
